services:
  back-end:
    build:
      context: pokedex-be
    container_name: back-end
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./pokedex-be:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "8000:8000"
    command: node ./bin/www

  front-end:
    build:
      context: pokedex-fe
    container_name: front-end
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./pokedex-fe:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm run dev

networks:
  node-network:
    driver: bridge
